SELECT *
FROM ( SELECT O.CODIGO, O.NOMBRE, COUNT(S.DNI) AS NUM_SOCIOS 
        FROM ONG O, SOCIO S
        WHERE S.DNI IN( SELECT C.SOCIO
                        FROM COLABORACION C
                        WHERE O.CODIGO=C.ONG)
        GROUP BY O.CODIGO, O.NOMBRE)
WHERE CODIGO='O01';
--9
SELECT *
FROM ( SELECT O.CODIGO, O.NOMBRE, COUNT(S.DNI) AS NUM_SOCIOS 
        FROM ONG O, SOCIO S
        WHERE S.DNI IN( SELECT C.SOCIO
                        FROM COLABORACION C
                        WHERE O.CODIGO=C.ONG)
        GROUP BY O.CODIGO, O.NOMBRE)
WHERE CODIGO='O02';
--4
ALTER TABLE COLABORACION DISABLE CONSTRAINT colaboracion_fk_ong;
UPDATE COLABORACION
SET ONG='TMP'
WHERE ONG='O01';
UPDATE COLABORACION
SET ONG='O01'
WHERE ONG='O02';
UPDATE COLABORACION
SET ONG='O02'
WHERE ONG='TMP';
ALTER TABLE COLABORACION ENABLE CONSTRAINT colaboracion_fk_ong;

SELECT *
FROM ( SELECT O.CODIGO, O.NOMBRE, COUNT(S.DNI) AS NUM_SOCIOS 
        FROM ONG O, SOCIO S
        WHERE S.DNI IN( SELECT C.SOCIO
                        FROM COLABORACION C
                        WHERE O.CODIGO=C.ONG)
        GROUP BY O.CODIGO, O.NOMBRE)
WHERE CODIGO='O01';
--4
SELECT *
FROM ( SELECT O.CODIGO, O.NOMBRE, COUNT(S.DNI) AS NUM_SOCIOS 
        FROM ONG O, SOCIO S
        WHERE S.DNI IN( SELECT C.SOCIO
                        FROM COLABORACION C
                        WHERE O.CODIGO=C.ONG)
        GROUP BY O.CODIGO, O.NOMBRE)
WHERE CODIGO='O02';
--9
ROLLBACK; --No funciona









