CREATE VIEW VOLUNTARIO
AS SELECT NOMBRE, ONG, PROFESION, HORAS
FROM TRABAJADOR
WHERE ESVOLUNTARIO='S';

SELECT * 
FROM VOLUNTARIO
ORDER BY ONG, NOMBRE;

CREATE OR REPLACE VIEW VOLUNTARIO
AS SELECT NOMBRE, ONG, HORAS
FROM TRABAJADOR
WHERE ESVOLUNTARIO='S';

SELECT * 
FROM VOLUNTARIO
ORDER BY ONG, NOMBRE;

UPDATE VOLUNTARIO
SET HORAS=HORAS+2
WHERE ESVOLUNTARIO='S';

SELECT * 
FROM VOLUNTARIO
ORDER BY ONG, NOMBRE;

SELECT * FROM TRABAJADOR;

INSERT INTO VOLUNTARIO
VALUES ('Alvaro Lopez Ayllon', 'O10', 10);

SELECT * 
FROM VOLUNTARIO
ORDER BY ONG, NOMBRE;

DROP VIEW VOLUNTARIO;


