--10
SELECT C.IDCASA, C.NOMBRE
FROM CASA C, PLAN P, TIPOPLAN T
WHERE C.IDCASA=P.CASA AND P.TIPOPLAN=T.IDTIPO AND T.NIVEL=5
GROUP BY C.IDCASA, C.NOMBRE
HAVING COUNT(DISTINCT P.TIPOPLAN) = (SELECT COUNT(*)
                                     FROM(SELECT P.TIPOPLAN, T.DESCRIPCION, T.NIVEL
                                          FROM PLAN P, TIPOPLAN T
                                          WHERE P.TIPOPLAN=T.IDTIPO AND T.NIVEL=5
                                          GROUP BY P.TIPOPLAN, T.DESCRIPCION, T.NIVEL))
ORDER BY IDCASA;